# Generated by Django 5.1.3 on 2024-11-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrow',
            options={'ordering': ['-created_at']},
        ),
    ]
